export const GAME_CONSTANTS = {
  PLAYER_RADIUS: 14,
  PLAYER_ACCEL: 0.45,
  PLAYER_FRICTION: 0.96,
  PLAYER_MAX_VEL: 8,
  PLAYER_ROT_SPEED: 0.15,
  PLAYER_MAX_HEARTS: 3,
  INVULN_FRAMES: 60,
  
  DASH_IMPULSE: 12,
  DASH_COOLDOWN_MS: 2000,
  DASH_DURATION_FRAMES: 10,

  BULLET_SPEED: 12,
  BULLET_COOLDOWN_MS: 300,
  BULLET_RADIUS: 4,
  BULLET_LIFE: 60,

  MONSTER_BULLET_SPEED: 6,
  MONSTER_SHOOT_INTERVAL_MS: 3000,
  MONSTER_BULLET_RADIUS: 5,

  BOMB_RADIUS: 250,
  BOMB_POINTS_RECHARGE: 100,

  HEART_RADIUS: 18,
  HEART_LIFETIME_MS: 6000,
  HEART_SPAWN_CHANCE: 0.002, // Small chance per frame in Level 3

  INITIAL_SPAWN_INTERVAL_MS: 1000,
  SPAWN_DECREMENT_INTERVAL_MS: 15000,
  SPAWN_DECREMENT_AMOUNT_MS: 100,
  MIN_SPAWN_INTERVAL_MS: 300,

  ASTEROID_MIN_RADIUS: 15,
  ASTEROID_MAX_RADIUS: 40,
  ASTEROID_MIN_SPEED: 1.5,
  ASTEROID_MAX_SPEED: 4,

  MONSTER_RADIUS: 18,
  MONSTER_INITIAL_SPEED: 1.2,
  MONSTER_SPEED_INC: 0.05,
  MONSTER_KILL_SPEED_INC: 0.15,
  MONSTER_SPAWN_START_MS: 8000,
  MONSTER_SPAWN_FAST_MS: 5000,
  MONSTER_MAX_COUNT: 5,
  MONSTER_ROT_SPEED: 0.04,

  POINTS_MONSTER: 50,
  POINTS_ASTEROID: 10,
  LEVEL_UP_KILLS: 3, // 3 kills needed to reach Level 2
  LEVEL_3_KILLS_TOTAL: 5, // 5 total kills (3 from L1 + 2 from L2) to reach Level 3

  PARTICLE_COUNT: 25,
  PARTICLE_LIFE: 60,
  TRAIL_LIFE: 15,
  
  STAR_COUNT: 100,
  SCREEN_SHAKE_DURATION: 18,
};